### ISSUE TITLE
Hooks are great

### ISSUE THREAD

**Issue by LaserFlash** [woodRock/woodrock.github.io#6]
Everything gets better with hooks, as React attempts to move to functional programming

Docs: https://reactjs.org/docs/hooks-reference.html
Style rule: https://www.npmjs.com/package/eslint-plugin-react-hooks (must use)

if you want I can rewrite one of your components / classes to be hooks based

**Comment by woodRock** [comment]
I will get their slowly. I have started to convert some of the pages over to react-hooks.

**Comment by woodRock** [comment]
# To Be Hooked 
- [x] Blog 
- [x] Copyright 
- [x] CV 
- [x] Education 
- [x] Home
- [x] Job 
- [x] Navigation 
- [x] Projects 
- [x] Skills 
- [x] Landing 
- [x] Loading 
- [x] Social 
- [x] Firebase
- [x] withMarkdown
- [x] withAuthentication
- [x] withAuthorization

**Comment by woodRock** [comment]
Doneskies
